<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deployment" nsURI="https://Y3884010/v2" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Deployment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="microservices" upperBound="-1"
        eType="#//Microservice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" upperBound="-1"
        eType="#//Topic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cliTool" eType="#//CliTool"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Microservice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaPackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producers" upperBound="-1"
        eType="#//Producer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serdeable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" eSuperTypes="#//JavaClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//Method" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transactional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//Request"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" upperBound="-1"
        eType="#//Response" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produced" upperBound="-1"
        eType="#//Topic"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientCommand" eType="#//Command"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verb" eType="#//HttpVerb"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//HttpCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpVerb">
    <eLiterals name="GET"/>
    <eLiterals name="PUT" value="1"/>
    <eLiterals name="POST" value="2"/>
    <eLiterals name="PATCH" value="3"/>
    <eLiterals name="DELETE" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpCode">
    <eLiterals name="OK"/>
    <eLiterals name="CREATED" value="1"/>
    <eLiterals name="NOT_FOUND" value="2"/>
    <eLiterals name="FORBIDDEN" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CliTool" eSuperTypes="#//JavaClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command" eSuperTypes="#//JavaClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllerMethod" eType="#//Method"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Producer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" upperBound="-1"
        eType="#//ProducerMethod" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProducerMethod">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topics" lowerBound="1"
        upperBound="-1" eType="#//Topic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Model">
    <eLiterals name="None"/>
    <eLiterals name="Long" value="1"/>
    <eLiterals name="String" value="2"/>
    <eLiterals name="Video" value="3"/>
    <eLiterals name="IterableVideo" value="4"/>
    <eLiterals name="IterableUser" value="5"/>
    <eLiterals name="VideoDTO" value="6"/>
    <eLiterals name="Hashtag" value="7"/>
    <eLiterals name="HashtagDTO" value="8"/>
    <eLiterals name="User" value="9"/>
    <eLiterals name="UserDTO" value="10"/>
    <eLiterals name="UserVideo" value="11"/>
    <eLiterals name="HashtagSet" value="12"/>
    <eLiterals name="Top10DTO" value="13"/>
    <eLiterals name="WatchlistDTO" value="14"/>
  </eClassifiers>
</ecore:EPackage>
