datasources:
  default:
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
    url: jdbc:mariadb://localhost:3306/videos
    username: todo
    password: todosecret
micronaut:
  application:
    name: subscription-microservice
  server:
    port: 8083
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.sm.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  consumers:
    auto:
      offset:
        reset: earliest
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
logger:
  levels:
    org.hibernate.SQL: WARN
subscription-microservice:
  kafka:
    topics:
      new-subscriptions: eng2-subscriptions
      new-videos: eng2-new-videos
      new-videos-by-user-hashtag: eng2-new-videos-by-user-hashtag
#      subscription-videos-by-user-hashtag: eng2-subscription-videos
      next-subscription-videos: eng2-next-subscription-videos
      watched-videos: eng2-watched-videos
      watched-videos-by-user-hashtag: eng2-watched-videos-by-user-hashtag
      new-sub-suggestions: eng2-new-sub-vid-suggestions
    stores:
      next-subscription-videos: next-subscription-videos-store
    misc:
      cleanup: true
